version: '3.8'

services:
  app:
    build:
      context: ./SpringbootCrud
      dockerfile: Dockerfile
    ports:
      - 8088:8088  
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springbootcrud?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./crudoperation
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springbootcrud
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
